<?xml version="1.0"?>
<robot name="hyperion_hypercomplex_mech" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ============= XACRO 宏定义 ============= -->
  <xacro:property name="PI" value="3.1415926535897931" />
  <xacro:property name="DEG_TO_RAD" value="0.017453292519943295" />
  
  <!-- 材料颜色定义 -->
  <material name="titanium">
    <color rgba="0.7 0.7 0.8 1.0"/>
  </material>
  <material name="carbon_fiber">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  <material name="emissive_blue">
    <color rgba="0.1 0.3 0.8 1.0"/>
  </material>
  
  <!-- 复杂关节参数宏 -->
  <xacro:macro name="complex_joint" params="name type parent child xyz rpy 
                                           axis xyz_limits:=*-1 1 
                                           effort_limits:=100 
                                           velocity_limits:=10
                                           damping:=0.7
                                           friction:=0.01
                                           spring_reference:=0
                                           spring_stiffness:=100">
    <joint name="${name}" type="${type}">
      <parent link="${parent}"/>
      <child link="${child}"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
      <axis xyz="${axis}"/>
      <limit lower="${xyz_limits.split()[0]}" 
             upper="${xyz_limits.split()[1]}" 
             effort="${effort_limits}" 
             velocity="${velocity_limits}"/>
      <dynamics damping="${damping}" friction="${friction}"/>
      <safety_controller soft_lower_limit="${xyz_limits.split()[0]}" 
                         soft_upper_limit="${xyz_limits.split()[1]}" 
                         k_position="100" k_velocity="10"/>
      <calibration rising="0.0" falling="0.0"/>
      <mimic joint="" multiplier="1.0" offset="0.0"/>
      <spring_reference>${spring_reference}</spring_reference>
      <spring_stiffness>${spring_stiffness}</spring_stiffness>
    </joint>
  </xacro:macro>

  <!-- 复杂连杆宏 -->
  <xacro:macro name="complex_link" params="name 
                                          mass:=10
                                          com_xyz:='0 0 0'
                                          com_rpy:='0 0 0'
                                          ixx:=0.1 ixy:=0 iyy:=0.1 ixz:=0 iyz:=0 izz:=0.1">
    <link name="${name}">
      <!-- 视觉部分 -->
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://hyperion_meshes/${name}.stl" scale="1 1 1"/>
        </geometry>
        <material name="titanium"/>
      </visual>
      
      <!-- 碰撞部分（简化模型） -->
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <compound>
            <box size="0.1 0.1 0.2"/>
            <cylinder radius="0.05" length="0.3"/>
            <sphere radius="0.08"/>
          </compound>
        </geometry>
      </collision>
      
      <!-- 惯量参数 -->
      <inertial>
        <origin xyz="${com_xyz}" rpy="${com_rpy}"/>
        <mass value="${mass}"/>
        <inertia ixx="${ixx}" ixy="${ixy}" ixz="${ixz}" 
                 iyy="${iyy}" iyz="${iyz}" izz="${izz}"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- 传感器宏 -->
  <xacro:macro name="lidar_sensor" params="name parent">
    <link name="${name}_link"/>
    <joint name="${name}_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}_link"/>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
    </joint>
    <gazebo reference="${name}_link">
      <sensor name="${name}" type="ray">
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <update_rate>40</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>720</samples>
              <resolution>1</resolution>
              <min_angle>-${180*DEG_TO_RAD}</min_angle>
              <max_angle>${180*DEG_TO_RAD}</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.1</min>
            <max>30.0</max>
            <resolution>0.03</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_${name}_controller" 
                filename="libgazebo_ros_laser.so">
          <topicName>/scan</topicName>
          <frameName>${name}_link</frameName>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>

  <!-- ============= 主机器人结构 ============= -->
  
  <!-- 基座 -->
  <complex_link name="base_link" mass="50" 
                ixx="1.0" iyy="1.0" izz="2.0"/>
  
  <!-- 主躯干 -->
  <complex_link name="torso" mass="30"/>
  <complex_joint name="torso_joint" type="continuous"
                parent="base_link" child="torso"
                xyz="0 0 0.5" rpy="0 0 0"
                axis="0 0 1"/>
  
  <!-- 头部（含多自由度） -->
  <complex_link name="head_base" mass="5"/>
  <complex_link name="head_pitch" mass="3"/>
  <complex_link name="head_yaw" mass="2"/>
  
  <complex_joint name="head_base_joint" type="revolute"
                parent="torso" child="head_base"
                xyz="0 0 0.8" rpy="0 0 0"
                axis="0 0 1"
                xyz_limits="-3.14 3.14"/>
  
  <complex_joint name="head_pitch_joint" type="revolute"
                parent="head_base" child="head_pitch"
                xyz="0 0 0.1" rpy="0 0 0"
                axis="0 1 0"
                xyz_limits="-1.57 1.57"/>
                
  <complex_joint name="head_yaw_joint" type="revolute"
                parent="head_pitch" child="head_yaw"
                xyz="0 0 0.05" rpy="0 0 0"
                axis="1 0 0"
                xyz_limits="-0.79 0.79"/>
  
  <!-- 左臂（7自由度） -->
  <xacro:property name="arm_mass" value="[2, 2, 1.5, 1, 0.5, 0.3, 0.2]" />
  <xacro:property name="arm_lengths" value="[0.1, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05]" />
  
  <xacro:macro name="build_arm" params="side">
    <xacro:foreach index="i" from="1" to="7" step="1">
      <complex_link name="${side}_arm_${i}" 
                    mass="${arm_mass[i-1]}"
                    com_xyz="0 0 ${arm_lengths[i-1]/2}"/>
      
      <xacro:if value="${i == 1}">
        <complex_joint name="${side}_shoulder_yaw" type="revolute"
                      parent="torso" child="${side}_arm_1"
                      xyz="${0.3 if side=='left' else -0.3} 0 0.7"
                      rpy="0 0 0"
                      axis="0 0 1"
                      xyz_limits="-2.09 2.09"/>
      </xacro:if>
      <xacro:if value="${i > 1}">
        <complex_joint name="${side}_joint_${i}" type="revolute"
                      parent="${side}_arm_${i-1}" child="${side}_arm_${i}"
                      xyz="0 0 ${arm_lengths[i-2]}"
                      rpy="0 0 0"
                      axis="${'0 1 0' if i%2==0 else '1 0 0'}"
                      xyz_limits="-1.57 1.57"/>
      </xacro:if>
    </xacro:foreach>
    
    <!-- 末端执行器 -->
    <link name="${side}_gripper_base">
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.001" ixy="0" ixz="0" 
                 iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>
    
    <joint name="${side}_gripper_joint" type="prismatic">
      <parent link="${side}_arm_7"/>
      <child link="${side}_gripper_base"/>
      <origin xyz="0 0 ${arm_lengths[6]}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.1" upper="0.1" effort="50" velocity="0.5"/>
    </joint>
    
    <!-- 夹爪手指 -->
    <xacro:foreach index="finger" from="1" to="2" step="1">
      <link name="${side}_finger_${finger}">
        <visual>
          <geometry>
            <box size="0.02 0.02 0.05"/>
          </geometry>
          <material name="carbon_fiber"/>
        </visual>
        <inertial>
          <mass value="0.1"/>
          <inertia ixx="0.0001" ixy="0" ixz="0" 
                   iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
      </link>
      
      <joint name="${side}_finger_${finger}_joint" type="revolute">
        <parent link="${side}_gripper_base"/>
        <child link="${side}_finger_${finger}"/>
        <origin xyz="${0.03 if finger==1 else -0.03} 0 0.025" 
                rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-0.5" upper="0.5" effort="20" velocity="1"/>
        <mimic joint="${side}_gripper_joint" 
               multiplier="${1 if finger==1 else -1}" 
               offset="0"/>
      </joint>
    </xacro:foreach>
  </xacro:macro>
  
  <!-- 构建双臂 -->
  <build_arm side="left"/>
  <build_arm side="right"/>
  
  <!-- 腿部（6自由度每条腿） -->
  <xacro:macro name="build_leg" params="side">
    <xacro:foreach index="i" from="1" to="6" step="1">
      <complex_link name="${side}_leg_${i}" mass="${10-i}"/>
      
      <xacro:if value="${i == 1}">
        <complex_joint name="${side}_hip_yaw" type="revolute"
                      parent="base_link" child="${side}_leg_1"
                      xyz="${0.2 if side=='left' else -0.2} 0 -0.3"
                      rpy="0 0 0"
                      axis="0 0 1"
                      xyz_limits="-0.79 0.79"/>
      </xacro:if>
      <xacro:if value="${i > 1}">
        <complex_joint name="${side}_leg_joint_${i}" type="revolute"
                      parent="${side}_leg_${i-1}" child="${side}_leg_${i}"
                      xyz="0 0 0.2"
                      rpy="0 0 0"
                      axis="${'0 1 0' if i%2==0 else '1 0 0'}"
                      xyz_limits="-2.09 2.09"/>
      </xacro:if>
    </xacro:foreach>
    
    <!-- 脚部 -->
    <link name="${side}_foot">
      <visual>
        <geometry>
          <mesh filename="package://hyperion_meshes/foot.stl"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <box size="0.15 0.1 0.05"/>
        </geometry>
      </collision>
    </link>
    
    <joint name="${side}_ankle_joint" type="spherical">
      <parent link="${side}_leg_6"/>
      <child link="${side}_foot"/>
      <origin xyz="0 0 0.2" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  
  <build_leg side="left"/>
  <build_leg side="right"/>
  
  <!-- ============= 传感器系统 ============= -->
  
  <!-- LIDAR -->
  <lidar_sensor name="main_lidar" parent="head_yaw"/>
  
  <!-- 相机 -->
  <link name="camera_link"/>
  <joint name="camera_joint" type="fixed">
    <parent link="head_yaw"/>
    <child link="camera_link"/>
    <origin xyz="0.1 0 0.05" rpy="0 0 0"/>
  </joint>
  
  <gazebo reference="camera_link">
    <sensor name="camera" type="camera">
      <update_rate>30</update_rate>
      <camera name="main_camera">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>1920</width>
          <height>1080</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" 
              filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>/hyperion/camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.07</hackBaseline>
      </plugin>
    </sensor>
  </gazebo>
  
  <!-- IMU -->
  <gazebo reference="torso">
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>1000</update_rate>
      <visualize>true</visualize>
      <topic>__default_topic__</topic>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <topicName>/imu/data</topicName>
        <bodyName>torso</bodyName>
        <updateRateHZ>1000.0</updateRateHZ>
        <gaussianNoise>0.00000001</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>torso</frameName>
        <initialOrientationAsReference>false</initialOrientationAsReference>
      </plugin>
      <pose>0 0 0 0 0 0</pose>
    </sensor>
  </gazebo>
  
  <!-- 力/力矩传感器 -->
  <gazebo>
    <plugin name="ft_sensor" filename="libgazebo_ros_ft_sensor.so">
      <updateRate>100.0</updateRate>
      <topicName>/force_torque</topicName>
      <jointName>left_wrist_joint</jointName>
      <noise>
        <type>gaussian</type>
        <mean>0.0</mean>
        <stddev>0.01</stddev>
      </noise>
    </plugin>
  </gazebo>
  
  <!-- ============= Gazebo 扩展 ============= -->
  
  <!-- 传输 -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/hyperion</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>
  
  <!-- 照明 -->
  <gazebo reference="head_yaw">
    <light type="spot" name="head_light">
      <pose>0.2 0 0 0 0 0</pose>
      <diffuse>1 1 1 1</diffuse>
      <specular>0.5 0.5 0.5 1</specular>
      <attenuation>
        <range>10</range>
        <constant>0.8</constant>
        <linear>0.01</linear>
        <quadratic>0.001</quadratic>
      </attenuation>
      <direction>1 0 0</direction>
      <spot>
        <inner_angle>0.3</inner_angle>
        <outer_angle>0.6</outer_angle>
        <falloff>1.0</falloff>
      </spot>
    </light>
  </gazebo>
  
  <!-- 材料属性 -->
  <gazebo reference="base_link">
    <material>Gazebo/Red</material>
    <mu1>0.8</mu1>
    <mu2>0.8</mu2>
    <kp>1000000</kp>
    <kd>100</kd>
    <minDepth>0.001</minDepth>
    <maxVel>1.0</maxVel>
  </gazebo>
  
  <!-- ============= ROS2 控制接口 ============= -->
  
  <!-- 关节状态发布器 -->
  <ros2_control name="hyperion_control" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="torso_joint">
      <command_interface name="velocity"/>
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <!-- 为所有关节添加类似配置 -->
  </ros2_control>
  
  <!-- MoveIt 配置 -->
  <xacro:property name="planning_groups">
    <group name="left_arm">
      <chain base_link="torso" tip_link="left_gripper_base"/>
      <joint name="left_shoulder_yaw"/>
      <!-- 添加所有左臂关节 -->
    </group>
    <group name="right_arm">
      <chain base_link="torso" tip_link="right_gripper_base"/>
    </group>
    <group name="both_arms">
      <group name="left_arm"/>
      <group name="right_arm"/>
    </group>
  </xacro:property>
  
  <!-- ============= 传输定义 ============= -->
  
  <!-- 为所有关节添加传输 -->
  <xacro:macro name="add_transmission" params="joint_name type:=hardware_interface/PositionJointInterface">
    <transmission name="${joint_name}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint_name}">
        <hardwareInterface>${type}</hardwareInterface>
      </joint>
      <actuator name="${joint_name}_motor">
        <hardwareInterface>${type}</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>
  
  <!-- 自动为所有关节添加传输 -->
  <xacro:add_transmission joint_name="torso_joint"/>
  <!-- 为其他所有关节重复此过程 -->
  
</robot>